In [4]:
P = [2 -1 -1 ;
    -1 2 -1;
    -1 -1 2]

3×3 Matrix{Int64}:
  2  -1  -1
 -1   2  -1
 -1  -1   2

In [ ]:
S = [0 1 4 ;
    1 01  1     

In [2]:
S = [0 1 4;
    1 0 1 ;
    4 1 0]

3×3 Matrix{Int64}:
 0  1  4
 1  0  1
 4  1  0

In [5]:
P*S

3×3 Matrix{Int64}:
 -5   1   7
 -2  -2  -2
  7   1  -5

In [6]:
P *S *P

3×3 Matrix{Int64}:
 -18  0   18
   0  0    0
  18  0  -18

In [7]:
D = [1 2;
     3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [8]:
DD = D.^2

2×2 Matrix{Int64}:
 1   4
 9  16

In [10]:
ones(3) * ones(3)'

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [18]:
using LinearAlgebra
G= DD
e = eigvals(G)
V = eigvecs(G)
@show e
count(e .>0)
Diagonal([1])

e = [-1.1046863561492728, 18.104686356149273]


1×1 Diagonal{Int64, Vector{Int64}}:
 1